### ISSUE TITLE
Don't work in typescript?

### ISSUE THREAD

**Issue by ralcorta** [jakwuh/deasync-promise#2]
Hi!

I'm developing a package in Typescript where i need to use promises in sync way. I installed this package and when i try to use it, the loop never end, I test it in many ways and never stop or enter in the success function until I stop the loop.

If I stop the loop, the promise will be resolved, but this isn't the idea. It's like the loop is blocking the thread?

How i can fix it? Its a bug or did it never work?

**Comment by rluvaton** [comment]
@ralcorta Did you solve the problem?
